/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef game_CONSTANTS_H
#define game_CONSTANTS_H

#include "game_types.h"



class gameConstants {
 public:
  gameConstants();

  std::map<GameError::type, std::string>  INVERR2STRING;
};

extern const gameConstants g_game_constants;



#endif
