/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef game_TYPES_H
#define game_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




struct ItemType {
  enum type {
    VIRTUAL = 1,
    CONTAINER = 2,
    WEAPON = 3,
    RAWMATERIAL = 4,
    REFINEDMATERIAL = 5
  };
};

extern const std::map<int, const char*> _ItemType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ItemType::type& val);

std::string to_string(const ItemType::type& val);

struct MobileType {
  enum type {
    PLAYER = 1,
    NPC = 2
  };
};

extern const std::map<int, const char*> _MobileType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const MobileType::type& val);

std::string to_string(const MobileType::type& val);

struct AttributeType {
  enum type {
    TRANSLATED_NAME = 1,
    TRANSLATED_SHORT_DESCRIPTION = 2,
    TRANSLATED_LONG_DESCRIPTION = 3,
    TRANSLATED_ASSET = 4,
    UNTRANSLATED_ASSET = 5,
    QUANTITY = 6,
    GALACTIC_POSITION = 7,
    SOLAR_POSITION = 8,
    GLOBAL_POSITION = 9,
    LOCAL_POSITION = 10,
    SIZE = 11,
    ITEM = 12,
    PURITY = 13,
    VOLUME = 14
  };
};

extern const std::map<int, const char*> _AttributeType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const AttributeType::type& val);

std::string to_string(const AttributeType::type& val);

struct StatusType {
  enum type {
    SUCCESS = 1,
    FAILURE = 2,
    SKIP = 3
  };
};

extern const std::map<int, const char*> _StatusType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const StatusType::type& val);

std::string to_string(const StatusType::type& val);

struct GameError {
  enum type {
    INV_MAX_ITEMS_REACHED = 1,
    INV_ALL_ENTRIES_MAX_STACKED = 2,
    INV_NEW_VOLUME_TOO_HIGH = 3,
    INV_CANNOT_ADD_ITEM = 4,
    INV_FAILED_TO_ADD = 5,
    INV_FAILED_TO_TRANSFER = 6,
    INV_COULD_NOT_FIND_ENTRY = 7,
    INV_NEW_QUANTITY_INVALID = 8,
    INV_FULL_CANNOT_SPLIT = 9,
    INV_ITEM_NOT_FOUND = 10,
    INV_INSUFFICIENT_QUANTITY = 11,
    INV_OPERATION_FAILED = 22,
    DB_CONNECTION_FAILED = 12,
    DB_TRANSACTION_FAILED = 13,
    DB_INSERT_FAILED = 14,
    DB_UPDATE_FAILED = 15,
    DB_DELETE_FAILED = 16,
    DB_QUERY_FAILED = 17,
    DB_RECORD_NOT_FOUND = 18,
    DB_INVALID_DATA = 19,
    DB_FOREIGN_KEY_VIOLATION = 20,
    DB_UNIQUE_CONSTRAINT_VIOLATION = 21
  };
};

extern const std::map<int, const char*> _GameError_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const GameError::type& val);

std::string to_string(const GameError::type& val);

typedef int64_t AssetId;

typedef int64_t ItemId;

typedef int64_t MobileId;

class Owner;

class ItemVector3;

class AttributeValue;

class Attribute;

class Item;

class ItemBlueprintComponent;

class ItemBlueprint;

class ItemDb;

class InventoryEntry;

class Inventory;

class GameResult;

class Mobile;

class LoadInventoryRequestData;

class CreateInventoryRequestData;

class SaveInventoryRequestData;

class SplitStackRequestData;

class TransferItemRequestData;

class LoadInventoryResponseData;

class CreateInventoryResponseData;

class SaveInventoryResponseData;

class SplitStackResponseData;

class TransferItemResponseData;

class RequestData;

class ResponseData;

class Request;

class Response;

class EnumDefinition;

class FieldEnumMapping;

class MethodDescription;

class ServiceMetadata;

typedef struct _Owner__isset {
  _Owner__isset() : mobile_id(false), item_id(false), asset_id(false) {}
  bool mobile_id :1;
  bool item_id :1;
  bool asset_id :1;
} _Owner__isset;

class Owner : public virtual ::apache::thrift::TBase {
 public:

  Owner(const Owner&) noexcept;
  Owner& operator=(const Owner&) noexcept;
  Owner() noexcept;

  virtual ~Owner() noexcept;
  MobileId mobile_id;
  ItemId item_id;
  AssetId asset_id;

  _Owner__isset __isset;

  void __set_mobile_id(const MobileId val);

  void __set_item_id(const ItemId val);

  void __set_asset_id(const AssetId val);

  bool operator == (const Owner & rhs) const;
  bool operator != (const Owner &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Owner & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Owner &a, Owner &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Owner& obj);

typedef struct _ItemVector3__isset {
  _ItemVector3__isset() : x(false), y(false), z(false) {}
  bool x :1;
  bool y :1;
  bool z :1;
} _ItemVector3__isset;

class ItemVector3 : public virtual ::apache::thrift::TBase {
 public:

  ItemVector3(const ItemVector3&) noexcept;
  ItemVector3& operator=(const ItemVector3&) noexcept;
  ItemVector3() noexcept;

  virtual ~ItemVector3() noexcept;
  double x;
  double y;
  double z;

  _ItemVector3__isset __isset;

  void __set_x(const double val);

  void __set_y(const double val);

  void __set_z(const double val);

  bool operator == (const ItemVector3 & rhs) const;
  bool operator != (const ItemVector3 &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ItemVector3 & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ItemVector3 &a, ItemVector3 &b) noexcept;

std::ostream& operator<<(std::ostream& out, const ItemVector3& obj);

typedef struct _AttributeValue__isset {
  _AttributeValue__isset() : bool_value(false), double_value(false), vector3(false), asset_id(false) {}
  bool bool_value :1;
  bool double_value :1;
  bool vector3 :1;
  bool asset_id :1;
} _AttributeValue__isset;

class AttributeValue : public virtual ::apache::thrift::TBase {
 public:

  AttributeValue(const AttributeValue&) noexcept;
  AttributeValue& operator=(const AttributeValue&) noexcept;
  AttributeValue() noexcept;

  virtual ~AttributeValue() noexcept;
  bool bool_value;
  double double_value;
  ItemVector3 vector3;
  AssetId asset_id;

  _AttributeValue__isset __isset;

  void __set_bool_value(const bool val);

  void __set_double_value(const double val);

  void __set_vector3(const ItemVector3& val);

  void __set_asset_id(const AssetId val);

  bool operator == (const AttributeValue & rhs) const;
  bool operator != (const AttributeValue &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AttributeValue & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(AttributeValue &a, AttributeValue &b) noexcept;

std::ostream& operator<<(std::ostream& out, const AttributeValue& obj);

typedef struct _Attribute__isset {
  _Attribute__isset() : id(false), internal_name(false), visible(false), value(false), attribute_type(false), owner(false) {}
  bool id :1;
  bool internal_name :1;
  bool visible :1;
  bool value :1;
  bool attribute_type :1;
  bool owner :1;
} _Attribute__isset;

class Attribute : public virtual ::apache::thrift::TBase {
 public:

  Attribute(const Attribute&);
  Attribute& operator=(const Attribute&);
  Attribute() noexcept;

  virtual ~Attribute() noexcept;
  int64_t id;
  std::string internal_name;
  bool visible;
  AttributeValue value;
  /**
   * 
   * @see AttributeType
   */
  AttributeType::type attribute_type;
  Owner owner;

  _Attribute__isset __isset;

  void __set_id(const int64_t val);

  void __set_internal_name(const std::string& val);

  void __set_visible(const bool val);

  void __set_value(const AttributeValue& val);

  void __set_attribute_type(const AttributeType::type val);

  void __set_owner(const Owner& val);

  bool operator == (const Attribute & rhs) const;
  bool operator != (const Attribute &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Attribute & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Attribute &a, Attribute &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Attribute& obj);

typedef struct _Item__isset {
  _Item__isset() : id(false), internal_name(false), attributes(false), max_stack_size(false), item_type(false), blueprint(false) {}
  bool id :1;
  bool internal_name :1;
  bool attributes :1;
  bool max_stack_size :1;
  bool item_type :1;
  bool blueprint :1;
} _Item__isset;

class Item : public virtual ::apache::thrift::TBase {
 public:

  Item(const Item&);
  Item& operator=(const Item&);
  Item() noexcept;

  virtual ~Item() noexcept;
  int64_t id;
  std::string internal_name;
  std::map<AttributeType::type, Attribute>  attributes;
  int64_t max_stack_size;
  /**
   * 
   * @see ItemType
   */
  ItemType::type item_type;
  ItemBlueprint blueprint;

  _Item__isset __isset;

  void __set_id(const int64_t val);

  void __set_internal_name(const std::string& val);

  void __set_attributes(const std::map<AttributeType::type, Attribute> & val);

  void __set_max_stack_size(const int64_t val);

  void __set_item_type(const ItemType::type val);

  void __set_blueprint(const ItemBlueprint& val);

  bool operator == (const Item & rhs) const;
  bool operator != (const Item &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Item & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Item &a, Item &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Item& obj);

typedef struct _ItemBlueprintComponent__isset {
  _ItemBlueprintComponent__isset() : ratio(false), item_id(false) {}
  bool ratio :1;
  bool item_id :1;
} _ItemBlueprintComponent__isset;

class ItemBlueprintComponent : public virtual ::apache::thrift::TBase {
 public:

  ItemBlueprintComponent(const ItemBlueprintComponent&) noexcept;
  ItemBlueprintComponent& operator=(const ItemBlueprintComponent&) noexcept;
  ItemBlueprintComponent() noexcept;

  virtual ~ItemBlueprintComponent() noexcept;
  double ratio;
  ItemId item_id;

  _ItemBlueprintComponent__isset __isset;

  void __set_ratio(const double val);

  void __set_item_id(const ItemId val);

  bool operator == (const ItemBlueprintComponent & rhs) const;
  bool operator != (const ItemBlueprintComponent &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ItemBlueprintComponent & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ItemBlueprintComponent &a, ItemBlueprintComponent &b) noexcept;

std::ostream& operator<<(std::ostream& out, const ItemBlueprintComponent& obj);

typedef struct _ItemBlueprint__isset {
  _ItemBlueprint__isset() : id(false), components(false), bake_time_ms(false) {}
  bool id :1;
  bool components :1;
  bool bake_time_ms :1;
} _ItemBlueprint__isset;

class ItemBlueprint : public virtual ::apache::thrift::TBase {
 public:

  ItemBlueprint(const ItemBlueprint&);
  ItemBlueprint& operator=(const ItemBlueprint&);
  ItemBlueprint() noexcept;

  virtual ~ItemBlueprint() noexcept;
  int64_t id;
  std::map<ItemId, ItemBlueprintComponent>  components;
  int64_t bake_time_ms;

  _ItemBlueprint__isset __isset;

  void __set_id(const int64_t val);

  void __set_components(const std::map<ItemId, ItemBlueprintComponent> & val);

  void __set_bake_time_ms(const int64_t val);

  bool operator == (const ItemBlueprint & rhs) const;
  bool operator != (const ItemBlueprint &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ItemBlueprint & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ItemBlueprint &a, ItemBlueprint &b) noexcept;

std::ostream& operator<<(std::ostream& out, const ItemBlueprint& obj);

typedef struct _ItemDb__isset {
  _ItemDb__isset() : items(false) {}
  bool items :1;
} _ItemDb__isset;

class ItemDb : public virtual ::apache::thrift::TBase {
 public:

  ItemDb(const ItemDb&);
  ItemDb& operator=(const ItemDb&);
  ItemDb() noexcept;

  virtual ~ItemDb() noexcept;
  std::vector<Item>  items;

  _ItemDb__isset __isset;

  void __set_items(const std::vector<Item> & val);

  bool operator == (const ItemDb & rhs) const;
  bool operator != (const ItemDb &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ItemDb & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ItemDb &a, ItemDb &b) noexcept;

std::ostream& operator<<(std::ostream& out, const ItemDb& obj);

typedef struct _InventoryEntry__isset {
  _InventoryEntry__isset() : item_id(false), quantity(false), is_max_stacked(true) {}
  bool item_id :1;
  bool quantity :1;
  bool is_max_stacked :1;
} _InventoryEntry__isset;

class InventoryEntry : public virtual ::apache::thrift::TBase {
 public:

  InventoryEntry(const InventoryEntry&) noexcept;
  InventoryEntry& operator=(const InventoryEntry&) noexcept;
  InventoryEntry() noexcept;

  virtual ~InventoryEntry() noexcept;
  ItemId item_id;
  double quantity;
  bool is_max_stacked;

  _InventoryEntry__isset __isset;

  void __set_item_id(const ItemId val);

  void __set_quantity(const double val);

  void __set_is_max_stacked(const bool val);

  bool operator == (const InventoryEntry & rhs) const;
  bool operator != (const InventoryEntry &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryEntry & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(InventoryEntry &a, InventoryEntry &b) noexcept;

std::ostream& operator<<(std::ostream& out, const InventoryEntry& obj);

typedef struct _Inventory__isset {
  _Inventory__isset() : id(false), max_entries(false), max_volume(false), entries(false), last_calculated_volume(true), owner(false) {}
  bool id :1;
  bool max_entries :1;
  bool max_volume :1;
  bool entries :1;
  bool last_calculated_volume :1;
  bool owner :1;
} _Inventory__isset;

class Inventory : public virtual ::apache::thrift::TBase {
 public:

  Inventory(const Inventory&);
  Inventory& operator=(const Inventory&);
  Inventory() noexcept;

  virtual ~Inventory() noexcept;
  int64_t id;
  int64_t max_entries;
  double max_volume;
  std::vector<InventoryEntry>  entries;
  double last_calculated_volume;
  Owner owner;

  _Inventory__isset __isset;

  void __set_id(const int64_t val);

  void __set_max_entries(const int64_t val);

  void __set_max_volume(const double val);

  void __set_entries(const std::vector<InventoryEntry> & val);

  void __set_last_calculated_volume(const double val);

  void __set_owner(const Owner& val);

  bool operator == (const Inventory & rhs) const;
  bool operator != (const Inventory &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Inventory & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Inventory &a, Inventory &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Inventory& obj);

typedef struct _GameResult__isset {
  _GameResult__isset() : status(false), message(false), error_code(false) {}
  bool status :1;
  bool message :1;
  bool error_code :1;
} _GameResult__isset;

class GameResult : public virtual ::apache::thrift::TBase {
 public:

  GameResult(const GameResult&);
  GameResult& operator=(const GameResult&);
  GameResult() noexcept;

  virtual ~GameResult() noexcept;
  /**
   * 
   * @see StatusType
   */
  StatusType::type status;
  std::string message;
  /**
   * 
   * @see GameError
   */
  GameError::type error_code;

  _GameResult__isset __isset;

  void __set_status(const StatusType::type val);

  void __set_message(const std::string& val);

  void __set_error_code(const GameError::type val);

  bool operator == (const GameResult & rhs) const;
  bool operator != (const GameResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GameResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(GameResult &a, GameResult &b) noexcept;

std::ostream& operator<<(std::ostream& out, const GameResult& obj);

typedef struct _Mobile__isset {
  _Mobile__isset() : id(false), mobile_type(false), attributes(false) {}
  bool id :1;
  bool mobile_type :1;
  bool attributes :1;
} _Mobile__isset;

class Mobile : public virtual ::apache::thrift::TBase {
 public:

  Mobile(const Mobile&);
  Mobile& operator=(const Mobile&);
  Mobile() noexcept;

  virtual ~Mobile() noexcept;
  MobileId id;
  /**
   * 
   * @see MobileType
   */
  MobileType::type mobile_type;
  std::map<AttributeType::type, Attribute>  attributes;

  _Mobile__isset __isset;

  void __set_id(const MobileId val);

  void __set_mobile_type(const MobileType::type val);

  void __set_attributes(const std::map<AttributeType::type, Attribute> & val);

  bool operator == (const Mobile & rhs) const;
  bool operator != (const Mobile &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Mobile & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Mobile &a, Mobile &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Mobile& obj);

typedef struct _LoadInventoryRequestData__isset {
  _LoadInventoryRequestData__isset() : inventory_id(false) {}
  bool inventory_id :1;
} _LoadInventoryRequestData__isset;

class LoadInventoryRequestData : public virtual ::apache::thrift::TBase {
 public:

  LoadInventoryRequestData(const LoadInventoryRequestData&) noexcept;
  LoadInventoryRequestData& operator=(const LoadInventoryRequestData&) noexcept;
  LoadInventoryRequestData() noexcept;

  virtual ~LoadInventoryRequestData() noexcept;
  int64_t inventory_id;

  _LoadInventoryRequestData__isset __isset;

  void __set_inventory_id(const int64_t val);

  bool operator == (const LoadInventoryRequestData & rhs) const;
  bool operator != (const LoadInventoryRequestData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LoadInventoryRequestData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LoadInventoryRequestData &a, LoadInventoryRequestData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const LoadInventoryRequestData& obj);

typedef struct _CreateInventoryRequestData__isset {
  _CreateInventoryRequestData__isset() : inventory(false) {}
  bool inventory :1;
} _CreateInventoryRequestData__isset;

class CreateInventoryRequestData : public virtual ::apache::thrift::TBase {
 public:

  CreateInventoryRequestData(const CreateInventoryRequestData&);
  CreateInventoryRequestData& operator=(const CreateInventoryRequestData&);
  CreateInventoryRequestData() noexcept;

  virtual ~CreateInventoryRequestData() noexcept;
  Inventory inventory;

  _CreateInventoryRequestData__isset __isset;

  void __set_inventory(const Inventory& val);

  bool operator == (const CreateInventoryRequestData & rhs) const;
  bool operator != (const CreateInventoryRequestData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CreateInventoryRequestData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CreateInventoryRequestData &a, CreateInventoryRequestData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const CreateInventoryRequestData& obj);

typedef struct _SaveInventoryRequestData__isset {
  _SaveInventoryRequestData__isset() : inventory(false) {}
  bool inventory :1;
} _SaveInventoryRequestData__isset;

class SaveInventoryRequestData : public virtual ::apache::thrift::TBase {
 public:

  SaveInventoryRequestData(const SaveInventoryRequestData&);
  SaveInventoryRequestData& operator=(const SaveInventoryRequestData&);
  SaveInventoryRequestData() noexcept;

  virtual ~SaveInventoryRequestData() noexcept;
  Inventory inventory;

  _SaveInventoryRequestData__isset __isset;

  void __set_inventory(const Inventory& val);

  bool operator == (const SaveInventoryRequestData & rhs) const;
  bool operator != (const SaveInventoryRequestData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SaveInventoryRequestData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SaveInventoryRequestData &a, SaveInventoryRequestData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const SaveInventoryRequestData& obj);

typedef struct _SplitStackRequestData__isset {
  _SplitStackRequestData__isset() : inventory_id(false), item_id(false), quantity_to_split(false) {}
  bool inventory_id :1;
  bool item_id :1;
  bool quantity_to_split :1;
} _SplitStackRequestData__isset;

class SplitStackRequestData : public virtual ::apache::thrift::TBase {
 public:

  SplitStackRequestData(const SplitStackRequestData&) noexcept;
  SplitStackRequestData& operator=(const SplitStackRequestData&) noexcept;
  SplitStackRequestData() noexcept;

  virtual ~SplitStackRequestData() noexcept;
  int64_t inventory_id;
  int64_t item_id;
  double quantity_to_split;

  _SplitStackRequestData__isset __isset;

  void __set_inventory_id(const int64_t val);

  void __set_item_id(const int64_t val);

  void __set_quantity_to_split(const double val);

  bool operator == (const SplitStackRequestData & rhs) const;
  bool operator != (const SplitStackRequestData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SplitStackRequestData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SplitStackRequestData &a, SplitStackRequestData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const SplitStackRequestData& obj);

typedef struct _TransferItemRequestData__isset {
  _TransferItemRequestData__isset() : source_inventory_id(false), destination_inventory_id(false), item_id(false), quantity(false) {}
  bool source_inventory_id :1;
  bool destination_inventory_id :1;
  bool item_id :1;
  bool quantity :1;
} _TransferItemRequestData__isset;

class TransferItemRequestData : public virtual ::apache::thrift::TBase {
 public:

  TransferItemRequestData(const TransferItemRequestData&) noexcept;
  TransferItemRequestData& operator=(const TransferItemRequestData&) noexcept;
  TransferItemRequestData() noexcept;

  virtual ~TransferItemRequestData() noexcept;
  int64_t source_inventory_id;
  int64_t destination_inventory_id;
  int64_t item_id;
  double quantity;

  _TransferItemRequestData__isset __isset;

  void __set_source_inventory_id(const int64_t val);

  void __set_destination_inventory_id(const int64_t val);

  void __set_item_id(const int64_t val);

  void __set_quantity(const double val);

  bool operator == (const TransferItemRequestData & rhs) const;
  bool operator != (const TransferItemRequestData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferItemRequestData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TransferItemRequestData &a, TransferItemRequestData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const TransferItemRequestData& obj);

typedef struct _LoadInventoryResponseData__isset {
  _LoadInventoryResponseData__isset() : inventory(false) {}
  bool inventory :1;
} _LoadInventoryResponseData__isset;

class LoadInventoryResponseData : public virtual ::apache::thrift::TBase {
 public:

  LoadInventoryResponseData(const LoadInventoryResponseData&);
  LoadInventoryResponseData& operator=(const LoadInventoryResponseData&);
  LoadInventoryResponseData() noexcept;

  virtual ~LoadInventoryResponseData() noexcept;
  Inventory inventory;

  _LoadInventoryResponseData__isset __isset;

  void __set_inventory(const Inventory& val);

  bool operator == (const LoadInventoryResponseData & rhs) const;
  bool operator != (const LoadInventoryResponseData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LoadInventoryResponseData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(LoadInventoryResponseData &a, LoadInventoryResponseData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const LoadInventoryResponseData& obj);

typedef struct _CreateInventoryResponseData__isset {
  _CreateInventoryResponseData__isset() : inventory(false) {}
  bool inventory :1;
} _CreateInventoryResponseData__isset;

class CreateInventoryResponseData : public virtual ::apache::thrift::TBase {
 public:

  CreateInventoryResponseData(const CreateInventoryResponseData&);
  CreateInventoryResponseData& operator=(const CreateInventoryResponseData&);
  CreateInventoryResponseData() noexcept;

  virtual ~CreateInventoryResponseData() noexcept;
  Inventory inventory;

  _CreateInventoryResponseData__isset __isset;

  void __set_inventory(const Inventory& val);

  bool operator == (const CreateInventoryResponseData & rhs) const;
  bool operator != (const CreateInventoryResponseData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CreateInventoryResponseData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CreateInventoryResponseData &a, CreateInventoryResponseData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const CreateInventoryResponseData& obj);

typedef struct _SaveInventoryResponseData__isset {
  _SaveInventoryResponseData__isset() : inventory(false) {}
  bool inventory :1;
} _SaveInventoryResponseData__isset;

class SaveInventoryResponseData : public virtual ::apache::thrift::TBase {
 public:

  SaveInventoryResponseData(const SaveInventoryResponseData&);
  SaveInventoryResponseData& operator=(const SaveInventoryResponseData&);
  SaveInventoryResponseData() noexcept;

  virtual ~SaveInventoryResponseData() noexcept;
  Inventory inventory;

  _SaveInventoryResponseData__isset __isset;

  void __set_inventory(const Inventory& val);

  bool operator == (const SaveInventoryResponseData & rhs) const;
  bool operator != (const SaveInventoryResponseData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SaveInventoryResponseData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SaveInventoryResponseData &a, SaveInventoryResponseData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const SaveInventoryResponseData& obj);

typedef struct _SplitStackResponseData__isset {
  _SplitStackResponseData__isset() : inventory(false) {}
  bool inventory :1;
} _SplitStackResponseData__isset;

class SplitStackResponseData : public virtual ::apache::thrift::TBase {
 public:

  SplitStackResponseData(const SplitStackResponseData&);
  SplitStackResponseData& operator=(const SplitStackResponseData&);
  SplitStackResponseData() noexcept;

  virtual ~SplitStackResponseData() noexcept;
  Inventory inventory;

  _SplitStackResponseData__isset __isset;

  void __set_inventory(const Inventory& val);

  bool operator == (const SplitStackResponseData & rhs) const;
  bool operator != (const SplitStackResponseData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SplitStackResponseData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SplitStackResponseData &a, SplitStackResponseData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const SplitStackResponseData& obj);

typedef struct _TransferItemResponseData__isset {
  _TransferItemResponseData__isset() : source_inventory(false), destination_inventory(false) {}
  bool source_inventory :1;
  bool destination_inventory :1;
} _TransferItemResponseData__isset;

class TransferItemResponseData : public virtual ::apache::thrift::TBase {
 public:

  TransferItemResponseData(const TransferItemResponseData&);
  TransferItemResponseData& operator=(const TransferItemResponseData&);
  TransferItemResponseData() noexcept;

  virtual ~TransferItemResponseData() noexcept;
  Inventory source_inventory;
  Inventory destination_inventory;

  _TransferItemResponseData__isset __isset;

  void __set_source_inventory(const Inventory& val);

  void __set_destination_inventory(const Inventory& val);

  bool operator == (const TransferItemResponseData & rhs) const;
  bool operator != (const TransferItemResponseData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferItemResponseData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(TransferItemResponseData &a, TransferItemResponseData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const TransferItemResponseData& obj);

typedef struct _RequestData__isset {
  _RequestData__isset() : load_inventory(false), create_inventory(false), save_inventory(false), split_stack(false), transfer_item(false) {}
  bool load_inventory :1;
  bool create_inventory :1;
  bool save_inventory :1;
  bool split_stack :1;
  bool transfer_item :1;
} _RequestData__isset;

class RequestData : public virtual ::apache::thrift::TBase {
 public:

  RequestData(const RequestData&);
  RequestData& operator=(const RequestData&);
  RequestData() noexcept;

  virtual ~RequestData() noexcept;
  LoadInventoryRequestData load_inventory;
  CreateInventoryRequestData create_inventory;
  SaveInventoryRequestData save_inventory;
  SplitStackRequestData split_stack;
  TransferItemRequestData transfer_item;

  _RequestData__isset __isset;

  void __set_load_inventory(const LoadInventoryRequestData& val);

  void __set_create_inventory(const CreateInventoryRequestData& val);

  void __set_save_inventory(const SaveInventoryRequestData& val);

  void __set_split_stack(const SplitStackRequestData& val);

  void __set_transfer_item(const TransferItemRequestData& val);

  bool operator == (const RequestData & rhs) const;
  bool operator != (const RequestData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RequestData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(RequestData &a, RequestData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const RequestData& obj);

typedef struct _ResponseData__isset {
  _ResponseData__isset() : load_inventory(false), create_inventory(false), save_inventory(false), split_stack(false), transfer_item(false) {}
  bool load_inventory :1;
  bool create_inventory :1;
  bool save_inventory :1;
  bool split_stack :1;
  bool transfer_item :1;
} _ResponseData__isset;

class ResponseData : public virtual ::apache::thrift::TBase {
 public:

  ResponseData(const ResponseData&);
  ResponseData& operator=(const ResponseData&);
  ResponseData() noexcept;

  virtual ~ResponseData() noexcept;
  LoadInventoryResponseData load_inventory;
  CreateInventoryResponseData create_inventory;
  SaveInventoryResponseData save_inventory;
  SplitStackResponseData split_stack;
  TransferItemResponseData transfer_item;

  _ResponseData__isset __isset;

  void __set_load_inventory(const LoadInventoryResponseData& val);

  void __set_create_inventory(const CreateInventoryResponseData& val);

  void __set_save_inventory(const SaveInventoryResponseData& val);

  void __set_split_stack(const SplitStackResponseData& val);

  void __set_transfer_item(const TransferItemResponseData& val);

  bool operator == (const ResponseData & rhs) const;
  bool operator != (const ResponseData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ResponseData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ResponseData &a, ResponseData &b) noexcept;

std::ostream& operator<<(std::ostream& out, const ResponseData& obj);

typedef struct _Request__isset {
  _Request__isset() : data(false) {}
  bool data :1;
} _Request__isset;

class Request : public virtual ::apache::thrift::TBase {
 public:

  Request(const Request&);
  Request& operator=(const Request&);
  Request() noexcept;

  virtual ~Request() noexcept;
  RequestData data;

  _Request__isset __isset;

  void __set_data(const RequestData& val);

  bool operator == (const Request & rhs) const;
  bool operator != (const Request &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Request & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Request &a, Request &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Request& obj);

typedef struct _Response__isset {
  _Response__isset() : results(false), response_data(false) {}
  bool results :1;
  bool response_data :1;
} _Response__isset;

class Response : public virtual ::apache::thrift::TBase {
 public:

  Response(const Response&);
  Response& operator=(const Response&);
  Response() noexcept;

  virtual ~Response() noexcept;
  std::vector<GameResult>  results;
  ResponseData response_data;

  _Response__isset __isset;

  void __set_results(const std::vector<GameResult> & val);

  void __set_response_data(const ResponseData& val);

  bool operator == (const Response & rhs) const;
  bool operator != (const Response &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Response & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Response &a, Response &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Response& obj);

typedef struct _EnumDefinition__isset {
  _EnumDefinition__isset() : enum_name(false), values(false), description(false) {}
  bool enum_name :1;
  bool values :1;
  bool description :1;
} _EnumDefinition__isset;

class EnumDefinition : public virtual ::apache::thrift::TBase {
 public:

  EnumDefinition(const EnumDefinition&);
  EnumDefinition& operator=(const EnumDefinition&);
  EnumDefinition() noexcept;

  virtual ~EnumDefinition() noexcept;
  std::string enum_name;
  std::map<std::string, int32_t>  values;
  std::string description;

  _EnumDefinition__isset __isset;

  void __set_enum_name(const std::string& val);

  void __set_values(const std::map<std::string, int32_t> & val);

  void __set_description(const std::string& val);

  bool operator == (const EnumDefinition & rhs) const;
  bool operator != (const EnumDefinition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EnumDefinition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(EnumDefinition &a, EnumDefinition &b) noexcept;

std::ostream& operator<<(std::ostream& out, const EnumDefinition& obj);

typedef struct _FieldEnumMapping__isset {
  _FieldEnumMapping__isset() : field_path(false), enum_name(false) {}
  bool field_path :1;
  bool enum_name :1;
} _FieldEnumMapping__isset;

class FieldEnumMapping : public virtual ::apache::thrift::TBase {
 public:

  FieldEnumMapping(const FieldEnumMapping&);
  FieldEnumMapping& operator=(const FieldEnumMapping&);
  FieldEnumMapping() noexcept;

  virtual ~FieldEnumMapping() noexcept;
  std::string field_path;
  std::string enum_name;

  _FieldEnumMapping__isset __isset;

  void __set_field_path(const std::string& val);

  void __set_enum_name(const std::string& val);

  bool operator == (const FieldEnumMapping & rhs) const;
  bool operator != (const FieldEnumMapping &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FieldEnumMapping & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(FieldEnumMapping &a, FieldEnumMapping &b) noexcept;

std::ostream& operator<<(std::ostream& out, const FieldEnumMapping& obj);

typedef struct _MethodDescription__isset {
  _MethodDescription__isset() : method_name(false), description(false), example_request_json(false), example_response_json(false), request_enum_fields(false), response_enum_fields(false) {}
  bool method_name :1;
  bool description :1;
  bool example_request_json :1;
  bool example_response_json :1;
  bool request_enum_fields :1;
  bool response_enum_fields :1;
} _MethodDescription__isset;

class MethodDescription : public virtual ::apache::thrift::TBase {
 public:

  MethodDescription(const MethodDescription&);
  MethodDescription& operator=(const MethodDescription&);
  MethodDescription() noexcept;

  virtual ~MethodDescription() noexcept;
  std::string method_name;
  std::string description;
  std::string example_request_json;
  std::string example_response_json;
  std::vector<FieldEnumMapping>  request_enum_fields;
  std::vector<FieldEnumMapping>  response_enum_fields;

  _MethodDescription__isset __isset;

  void __set_method_name(const std::string& val);

  void __set_description(const std::string& val);

  void __set_example_request_json(const std::string& val);

  void __set_example_response_json(const std::string& val);

  void __set_request_enum_fields(const std::vector<FieldEnumMapping> & val);

  void __set_response_enum_fields(const std::vector<FieldEnumMapping> & val);

  bool operator == (const MethodDescription & rhs) const;
  bool operator != (const MethodDescription &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MethodDescription & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(MethodDescription &a, MethodDescription &b) noexcept;

std::ostream& operator<<(std::ostream& out, const MethodDescription& obj);

typedef struct _ServiceMetadata__isset {
  _ServiceMetadata__isset() : service_name(false), version(false), description(false), methods(false), enums(false) {}
  bool service_name :1;
  bool version :1;
  bool description :1;
  bool methods :1;
  bool enums :1;
} _ServiceMetadata__isset;

class ServiceMetadata : public virtual ::apache::thrift::TBase {
 public:

  ServiceMetadata(const ServiceMetadata&);
  ServiceMetadata& operator=(const ServiceMetadata&);
  ServiceMetadata() noexcept;

  virtual ~ServiceMetadata() noexcept;
  std::string service_name;
  std::string version;
  std::string description;
  std::vector<MethodDescription>  methods;
  std::vector<EnumDefinition>  enums;

  _ServiceMetadata__isset __isset;

  void __set_service_name(const std::string& val);

  void __set_version(const std::string& val);

  void __set_description(const std::string& val);

  void __set_methods(const std::vector<MethodDescription> & val);

  void __set_enums(const std::vector<EnumDefinition> & val);

  bool operator == (const ServiceMetadata & rhs) const;
  bool operator != (const ServiceMetadata &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServiceMetadata & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ServiceMetadata &a, ServiceMetadata &b) noexcept;

std::ostream& operator<<(std::ostream& out, const ServiceMetadata& obj);



#endif
