/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "game_constants.h"



const gameConstants g_game_constants;

gameConstants::gameConstants() {
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(12), "database connection failed"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(16), "database delete operation failed"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(20), "foreign key constraint violation"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(14), "database insert operation failed"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(19), "invalid data provided for database operation"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(17), "database query failed"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(18), "database record not found"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(13), "database transaction failed"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(21), "unique constraint violation"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(15), "database update operation failed"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(2), "item is in inventory, but all entries are max stacked"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(4), "cannot add this item to the inventory"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(7), "could not find entry"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(5), "failed to add to inventory"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(6), "failed to transfer"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(9), "inventory is full, cannot split entry"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(11), "insufficient quantity available"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(10), "item not found in inventory"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(1), "item is not in inventory, and inventory has reached max items"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(8), "the new_quantity must be less than, and not equal to, the current entry.quantity"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(3), "the new_volume is too high"));
  INVERR2STRING.insert(std::make_pair(static_cast<GameError::type>(22), "inventory operation failed"));

}



