/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef InventoryService_H
#define InventoryService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "game_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class InventoryServiceIf {
 public:
  virtual ~InventoryServiceIf() {}
  virtual void describe(ServiceMetadata& _return) = 0;
  virtual void load(Response& _return, const Request& request) = 0;
  virtual void create(Response& _return, const Request& request) = 0;
  virtual void save(Response& _return, const Request& request) = 0;
  virtual void split_stack(Response& _return, const Request& request) = 0;
  virtual void transfer_item(Response& _return, const Request& request) = 0;
};

class InventoryServiceIfFactory {
 public:
  typedef InventoryServiceIf Handler;

  virtual ~InventoryServiceIfFactory() {}

  virtual InventoryServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(InventoryServiceIf* /* handler */) = 0;
  };

class InventoryServiceIfSingletonFactory : virtual public InventoryServiceIfFactory {
 public:
  InventoryServiceIfSingletonFactory(const ::std::shared_ptr<InventoryServiceIf>& iface) : iface_(iface) {}
  virtual ~InventoryServiceIfSingletonFactory() {}

  virtual InventoryServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(InventoryServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<InventoryServiceIf> iface_;
};

class InventoryServiceNull : virtual public InventoryServiceIf {
 public:
  virtual ~InventoryServiceNull() {}
  void describe(ServiceMetadata& /* _return */) override {
    return;
  }
  void load(Response& /* _return */, const Request& /* request */) override {
    return;
  }
  void create(Response& /* _return */, const Request& /* request */) override {
    return;
  }
  void save(Response& /* _return */, const Request& /* request */) override {
    return;
  }
  void split_stack(Response& /* _return */, const Request& /* request */) override {
    return;
  }
  void transfer_item(Response& /* _return */, const Request& /* request */) override {
    return;
  }
};


class InventoryService_describe_args {
 public:

  InventoryService_describe_args(const InventoryService_describe_args&) noexcept;
  InventoryService_describe_args& operator=(const InventoryService_describe_args&) noexcept;
  InventoryService_describe_args() noexcept;

  virtual ~InventoryService_describe_args() noexcept;

  bool operator == (const InventoryService_describe_args & /* rhs */) const;
  bool operator != (const InventoryService_describe_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_describe_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class InventoryService_describe_pargs {
 public:


  virtual ~InventoryService_describe_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_describe_result__isset {
  _InventoryService_describe_result__isset() : success(false) {}
  bool success :1;
} _InventoryService_describe_result__isset;

class InventoryService_describe_result {
 public:

  InventoryService_describe_result(const InventoryService_describe_result&);
  InventoryService_describe_result& operator=(const InventoryService_describe_result&);
  InventoryService_describe_result() noexcept;

  virtual ~InventoryService_describe_result() noexcept;
  ServiceMetadata success;

  _InventoryService_describe_result__isset __isset;

  void __set_success(const ServiceMetadata& val);

  bool operator == (const InventoryService_describe_result & rhs) const;
  bool operator != (const InventoryService_describe_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_describe_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_describe_presult__isset {
  _InventoryService_describe_presult__isset() : success(false) {}
  bool success :1;
} _InventoryService_describe_presult__isset;

class InventoryService_describe_presult {
 public:


  virtual ~InventoryService_describe_presult() noexcept;
  ServiceMetadata* success;

  _InventoryService_describe_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _InventoryService_load_args__isset {
  _InventoryService_load_args__isset() : request(false) {}
  bool request :1;
} _InventoryService_load_args__isset;

class InventoryService_load_args {
 public:

  InventoryService_load_args(const InventoryService_load_args&);
  InventoryService_load_args& operator=(const InventoryService_load_args&);
  InventoryService_load_args() noexcept;

  virtual ~InventoryService_load_args() noexcept;
  Request request;

  _InventoryService_load_args__isset __isset;

  void __set_request(const Request& val);

  bool operator == (const InventoryService_load_args & rhs) const;
  bool operator != (const InventoryService_load_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_load_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class InventoryService_load_pargs {
 public:


  virtual ~InventoryService_load_pargs() noexcept;
  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_load_result__isset {
  _InventoryService_load_result__isset() : success(false) {}
  bool success :1;
} _InventoryService_load_result__isset;

class InventoryService_load_result {
 public:

  InventoryService_load_result(const InventoryService_load_result&);
  InventoryService_load_result& operator=(const InventoryService_load_result&);
  InventoryService_load_result() noexcept;

  virtual ~InventoryService_load_result() noexcept;
  Response success;

  _InventoryService_load_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const InventoryService_load_result & rhs) const;
  bool operator != (const InventoryService_load_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_load_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_load_presult__isset {
  _InventoryService_load_presult__isset() : success(false) {}
  bool success :1;
} _InventoryService_load_presult__isset;

class InventoryService_load_presult {
 public:


  virtual ~InventoryService_load_presult() noexcept;
  Response* success;

  _InventoryService_load_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _InventoryService_create_args__isset {
  _InventoryService_create_args__isset() : request(false) {}
  bool request :1;
} _InventoryService_create_args__isset;

class InventoryService_create_args {
 public:

  InventoryService_create_args(const InventoryService_create_args&);
  InventoryService_create_args& operator=(const InventoryService_create_args&);
  InventoryService_create_args() noexcept;

  virtual ~InventoryService_create_args() noexcept;
  Request request;

  _InventoryService_create_args__isset __isset;

  void __set_request(const Request& val);

  bool operator == (const InventoryService_create_args & rhs) const;
  bool operator != (const InventoryService_create_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_create_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class InventoryService_create_pargs {
 public:


  virtual ~InventoryService_create_pargs() noexcept;
  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_create_result__isset {
  _InventoryService_create_result__isset() : success(false) {}
  bool success :1;
} _InventoryService_create_result__isset;

class InventoryService_create_result {
 public:

  InventoryService_create_result(const InventoryService_create_result&);
  InventoryService_create_result& operator=(const InventoryService_create_result&);
  InventoryService_create_result() noexcept;

  virtual ~InventoryService_create_result() noexcept;
  Response success;

  _InventoryService_create_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const InventoryService_create_result & rhs) const;
  bool operator != (const InventoryService_create_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_create_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_create_presult__isset {
  _InventoryService_create_presult__isset() : success(false) {}
  bool success :1;
} _InventoryService_create_presult__isset;

class InventoryService_create_presult {
 public:


  virtual ~InventoryService_create_presult() noexcept;
  Response* success;

  _InventoryService_create_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _InventoryService_save_args__isset {
  _InventoryService_save_args__isset() : request(false) {}
  bool request :1;
} _InventoryService_save_args__isset;

class InventoryService_save_args {
 public:

  InventoryService_save_args(const InventoryService_save_args&);
  InventoryService_save_args& operator=(const InventoryService_save_args&);
  InventoryService_save_args() noexcept;

  virtual ~InventoryService_save_args() noexcept;
  Request request;

  _InventoryService_save_args__isset __isset;

  void __set_request(const Request& val);

  bool operator == (const InventoryService_save_args & rhs) const;
  bool operator != (const InventoryService_save_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_save_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class InventoryService_save_pargs {
 public:


  virtual ~InventoryService_save_pargs() noexcept;
  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_save_result__isset {
  _InventoryService_save_result__isset() : success(false) {}
  bool success :1;
} _InventoryService_save_result__isset;

class InventoryService_save_result {
 public:

  InventoryService_save_result(const InventoryService_save_result&);
  InventoryService_save_result& operator=(const InventoryService_save_result&);
  InventoryService_save_result() noexcept;

  virtual ~InventoryService_save_result() noexcept;
  Response success;

  _InventoryService_save_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const InventoryService_save_result & rhs) const;
  bool operator != (const InventoryService_save_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_save_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_save_presult__isset {
  _InventoryService_save_presult__isset() : success(false) {}
  bool success :1;
} _InventoryService_save_presult__isset;

class InventoryService_save_presult {
 public:


  virtual ~InventoryService_save_presult() noexcept;
  Response* success;

  _InventoryService_save_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _InventoryService_split_stack_args__isset {
  _InventoryService_split_stack_args__isset() : request(false) {}
  bool request :1;
} _InventoryService_split_stack_args__isset;

class InventoryService_split_stack_args {
 public:

  InventoryService_split_stack_args(const InventoryService_split_stack_args&);
  InventoryService_split_stack_args& operator=(const InventoryService_split_stack_args&);
  InventoryService_split_stack_args() noexcept;

  virtual ~InventoryService_split_stack_args() noexcept;
  Request request;

  _InventoryService_split_stack_args__isset __isset;

  void __set_request(const Request& val);

  bool operator == (const InventoryService_split_stack_args & rhs) const;
  bool operator != (const InventoryService_split_stack_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_split_stack_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class InventoryService_split_stack_pargs {
 public:


  virtual ~InventoryService_split_stack_pargs() noexcept;
  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_split_stack_result__isset {
  _InventoryService_split_stack_result__isset() : success(false) {}
  bool success :1;
} _InventoryService_split_stack_result__isset;

class InventoryService_split_stack_result {
 public:

  InventoryService_split_stack_result(const InventoryService_split_stack_result&);
  InventoryService_split_stack_result& operator=(const InventoryService_split_stack_result&);
  InventoryService_split_stack_result() noexcept;

  virtual ~InventoryService_split_stack_result() noexcept;
  Response success;

  _InventoryService_split_stack_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const InventoryService_split_stack_result & rhs) const;
  bool operator != (const InventoryService_split_stack_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_split_stack_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_split_stack_presult__isset {
  _InventoryService_split_stack_presult__isset() : success(false) {}
  bool success :1;
} _InventoryService_split_stack_presult__isset;

class InventoryService_split_stack_presult {
 public:


  virtual ~InventoryService_split_stack_presult() noexcept;
  Response* success;

  _InventoryService_split_stack_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _InventoryService_transfer_item_args__isset {
  _InventoryService_transfer_item_args__isset() : request(false) {}
  bool request :1;
} _InventoryService_transfer_item_args__isset;

class InventoryService_transfer_item_args {
 public:

  InventoryService_transfer_item_args(const InventoryService_transfer_item_args&);
  InventoryService_transfer_item_args& operator=(const InventoryService_transfer_item_args&);
  InventoryService_transfer_item_args() noexcept;

  virtual ~InventoryService_transfer_item_args() noexcept;
  Request request;

  _InventoryService_transfer_item_args__isset __isset;

  void __set_request(const Request& val);

  bool operator == (const InventoryService_transfer_item_args & rhs) const;
  bool operator != (const InventoryService_transfer_item_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_transfer_item_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class InventoryService_transfer_item_pargs {
 public:


  virtual ~InventoryService_transfer_item_pargs() noexcept;
  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_transfer_item_result__isset {
  _InventoryService_transfer_item_result__isset() : success(false) {}
  bool success :1;
} _InventoryService_transfer_item_result__isset;

class InventoryService_transfer_item_result {
 public:

  InventoryService_transfer_item_result(const InventoryService_transfer_item_result&);
  InventoryService_transfer_item_result& operator=(const InventoryService_transfer_item_result&);
  InventoryService_transfer_item_result() noexcept;

  virtual ~InventoryService_transfer_item_result() noexcept;
  Response success;

  _InventoryService_transfer_item_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const InventoryService_transfer_item_result & rhs) const;
  bool operator != (const InventoryService_transfer_item_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InventoryService_transfer_item_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _InventoryService_transfer_item_presult__isset {
  _InventoryService_transfer_item_presult__isset() : success(false) {}
  bool success :1;
} _InventoryService_transfer_item_presult__isset;

class InventoryService_transfer_item_presult {
 public:


  virtual ~InventoryService_transfer_item_presult() noexcept;
  Response* success;

  _InventoryService_transfer_item_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class InventoryServiceClient : virtual public InventoryServiceIf {
 public:
  InventoryServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  InventoryServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void describe(ServiceMetadata& _return) override;
  void send_describe();
  void recv_describe(ServiceMetadata& _return);
  void load(Response& _return, const Request& request) override;
  void send_load(const Request& request);
  void recv_load(Response& _return);
  void create(Response& _return, const Request& request) override;
  void send_create(const Request& request);
  void recv_create(Response& _return);
  void save(Response& _return, const Request& request) override;
  void send_save(const Request& request);
  void recv_save(Response& _return);
  void split_stack(Response& _return, const Request& request) override;
  void send_split_stack(const Request& request);
  void recv_split_stack(Response& _return);
  void transfer_item(Response& _return, const Request& request) override;
  void send_transfer_item(const Request& request);
  void recv_transfer_item(Response& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class InventoryServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<InventoryServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (InventoryServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_describe(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_load(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_create(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_save(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_split_stack(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_transfer_item(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  InventoryServiceProcessor(::std::shared_ptr<InventoryServiceIf> iface) :
    iface_(iface) {
    processMap_["describe"] = &InventoryServiceProcessor::process_describe;
    processMap_["load"] = &InventoryServiceProcessor::process_load;
    processMap_["create"] = &InventoryServiceProcessor::process_create;
    processMap_["save"] = &InventoryServiceProcessor::process_save;
    processMap_["split_stack"] = &InventoryServiceProcessor::process_split_stack;
    processMap_["transfer_item"] = &InventoryServiceProcessor::process_transfer_item;
  }

  virtual ~InventoryServiceProcessor() {}
};

class InventoryServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  InventoryServiceProcessorFactory(const ::std::shared_ptr< InventoryServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< InventoryServiceIfFactory > handlerFactory_;
};

class InventoryServiceMultiface : virtual public InventoryServiceIf {
 public:
  InventoryServiceMultiface(std::vector<std::shared_ptr<InventoryServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~InventoryServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<InventoryServiceIf> > ifaces_;
  InventoryServiceMultiface() {}
  void add(::std::shared_ptr<InventoryServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void describe(ServiceMetadata& _return) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->describe(_return);
    }
    ifaces_[i]->describe(_return);
    return;
  }

  void load(Response& _return, const Request& request) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->load(_return, request);
    }
    ifaces_[i]->load(_return, request);
    return;
  }

  void create(Response& _return, const Request& request) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->create(_return, request);
    }
    ifaces_[i]->create(_return, request);
    return;
  }

  void save(Response& _return, const Request& request) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->save(_return, request);
    }
    ifaces_[i]->save(_return, request);
    return;
  }

  void split_stack(Response& _return, const Request& request) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->split_stack(_return, request);
    }
    ifaces_[i]->split_stack(_return, request);
    return;
  }

  void transfer_item(Response& _return, const Request& request) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->transfer_item(_return, request);
    }
    ifaces_[i]->transfer_item(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class InventoryServiceConcurrentClient : virtual public InventoryServiceIf {
 public:
  InventoryServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  InventoryServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void describe(ServiceMetadata& _return) override;
  int32_t send_describe();
  void recv_describe(ServiceMetadata& _return, const int32_t seqid);
  void load(Response& _return, const Request& request) override;
  int32_t send_load(const Request& request);
  void recv_load(Response& _return, const int32_t seqid);
  void create(Response& _return, const Request& request) override;
  int32_t send_create(const Request& request);
  void recv_create(Response& _return, const int32_t seqid);
  void save(Response& _return, const Request& request) override;
  int32_t send_save(const Request& request);
  void recv_save(Response& _return, const int32_t seqid);
  void split_stack(Response& _return, const Request& request) override;
  int32_t send_split_stack(const Request& request);
  void recv_split_stack(Response& _return, const int32_t seqid);
  void transfer_item(Response& _return, const Request& request) override;
  int32_t send_transfer_item(const Request& request);
  void recv_transfer_item(Response& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
