// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "InventoryService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class InventoryServiceHandler : virtual public InventoryServiceIf {
 public:
  InventoryServiceHandler() {
    // Your initialization goes here
  }

  void describe(ServiceMetadata& _return) {
    // Your implementation goes here
    printf("describe\n");
  }

  void load(Response& _return, const Request& request) {
    // Your implementation goes here
    printf("load\n");
  }

  void create(Response& _return, const Request& request) {
    // Your implementation goes here
    printf("create\n");
  }

  void save(Response& _return, const Request& request) {
    // Your implementation goes here
    printf("save\n");
  }

  void split_stack(Response& _return, const Request& request) {
    // Your implementation goes here
    printf("split_stack\n");
  }

  void transfer_item(Response& _return, const Request& request) {
    // Your implementation goes here
    printf("transfer_item\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<InventoryServiceHandler> handler(new InventoryServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new InventoryServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

