#
# Autogenerated by Thrift Compiler (0.23.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
from .ttypes import *
INVERR2STRING = {
        12: "database connection failed",
        16: "database delete operation failed",
        20: "foreign key constraint violation",
        14: "database insert operation failed",
        19: "invalid data provided for database operation",
        17: "database query failed",
        18: "database record not found",
        13: "database transaction failed",
        21: "unique constraint violation",
        15: "database update operation failed",
        2: "item is in inventory, but all entries are max stacked",
        4: "cannot add this item to the inventory",
        7: "could not find entry",
        5: "failed to add to inventory",
        6: "failed to transfer",
        9: "inventory is full, cannot split entry",
        11: "insufficient quantity available",
        10: "item not found in inventory",
        1: "item is not in inventory, and inventory has reached max items",
        8: "the new_quantity must be less than, and not equal to, the current entry.quantity",
        3: "the new_volume is too high",
        22: "inventory operation failed",
}
